### ISSUE TITLE
Unable to install the extension

### ISSUE THREAD

**Issue by varapmsft** [duckdblabs/duckdb_azure#12]
Hello,

I see below error when I try to install the extension in Windows. Please take a look.

```
D INSTALL azure;
Error: HTTP Error: Failed to download extension "azure" at URL "http://extensions.duckdb.org/v0.8.1/windows_amd64/azure.duckdb_extension.gz"

Candidate extensions: "icu"
```

**Comment by samansmink** [comment]
Hi, the azure extension is only available from 0.9.0, so this is expected, if you update DuckDB to the latest version this should work!
