### ISSUE TITLE
Sample query to read Parquet/CSV from Azure Blob Storage

### ISSUE THREAD

**Issue by AlessandroLollo** [duckdblabs/duckdb_azure#17]
https://github.com/duckdblabs/duckdb_azure/blob/77f343c3997b3bcca8f389f0fd43b9acf4ee9622/README.md?plain=1#L13

Hey folks 👋 

I think the query above, for Parquet files, should be
```
SELECT count(*)
FROM read_parquet('azure://<my_container>/<my_file>.parquet'); 
```

while for CSV files, it should be
```
SELECT count(*)
FROM read_csv('azure://<my_container>/<my_file>.csv'); 
```

**Comment by samansmink** [comment]
Hi @AlessandroLollo! Weell, ackshually both should work through the power of [replacement scans](https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/function/replacement_scan.hpp)

**Comment by samansmink** [comment]
Ah, the extension needs to be loaded first, check out the docs https://duckdb.org/docs/extensions/azure.

For some extensions we can autoload it, but this is not yet the case for azure.

**Comment by AlessandroLollo** [comment]
Sorry, I forgot to mention that I loaded the Azure extension before running the query.
